document.writeln("<div class=\"index-bg\">");
document.writeln("    <style type=\"text/css\">");
document.writeln("		/*commom style*/");
document.writeln("		*,*:before,*:after {box-sizing: border-box;-webkit-box-sizing: border-box;-moz-box-sizing: border-box;}");
document.writeln("		html,body,div,span,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,abbr,address,cite,code,del,dfn,em,img,ins,kbd,q,samp,small,");
document.writeln("		strong,sub,sup,var,b,i,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,");
document.writeln("		details,figcaption,figure,footer,header,hgroup,menu,nav,section,summary,time,mark,audio,video");
document.writeln("		{margin:0;padding:0;border:0;outline:none;}");
document.writeln("		input{margin:0;padding:0;outline:none;}");
document.writeln("		li{list-style:none;}");
document.writeln("		a,ins{text-decoration:none;}");
document.writeln("		*:focus{outline:none;}");
document.writeln("		a{color:#000000;}");
document.writeln("		/*a:hover{color:#2763ce;transition:all 0.2s;-webkit-transition:all 0.2s;-o-transition:all 0.2s;-moz-transition:all 0.2s;}*/");
document.writeln("		.fl{float:left;}");
document.writeln("		.fr{float:right;}");
document.writeln("		.cf:after{display:block;content:\'\';height:0;visibility:hidden;clear:both;}");
document.writeln("		.cf{zoom:1;}");
document.writeln("		.hide{display:none;}");
document.writeln("		.block{display:block;}");
document.writeln("		body{background:url(images/rbh_bg.jpg) no-repeat fixed;font-family:\'微软雅黑\';color:#000000; -moz-background-size: cover;-webkit-background-size:cover;background-size ：cover;}");
document.writeln("		");
document.writeln("		.center {");
document.writeln("		    margin: 0 auto;");
document.writeln("		}");
document.writeln("		");
document.writeln("		.w1200 {");
document.writeln("		    width: 1200px;");
document.writeln("		}");
document.writeln("		");
document.writeln("		/*效果*/");
document.writeln("	.index-bg {");
document.writeln("	    z-index: 0;");
document.writeln("	    width: auto;");
document.writeln("	    height: 100%;");
document.writeln("	    top: 0px;");
document.writeln("	}");
document.writeln("	.head-bg{");
document.writeln("	    height: 61px;");
document.writeln("	    width: 100%;");
document.writeln("	    border-bottom: solid 1px #c2b1ed;");
document.writeln("	}");
document.writeln("	.logo{");
document.writeln("	    width: 274px;");
document.writeln("	    height: 53px;");
document.writeln("	    margin-top: 3px;");
document.writeln("	    margin-left: 20px;");
document.writeln("	    background: url(\"images/logo.png\");" );
document.writeln("	}");
document.writeln("	.button-right {");
document.writeln("	    width: 65px;");
document.writeln("	    height: 60px;");
document.writeln("	    background: url(\"images/njblh-img1.png\") no-repeat;");
document.writeln("	    z-index: 1;");
document.writeln("	    top: 0px;");
document.writeln("	    right: 0px;");
document.writeln("	}");
document.writeln("	");
document.writeln(".input2{");
document.writeln("    height: 60px;");
document.writeln("    width: 312px;");
document.writeln("    position: absolute;");
document.writeln("	right: 120px;");
document.writeln("	padding: 10px;");
document.writeln("	top: 0;");
document.writeln("}");
document.writeln(".input2 input{");
document.writeln("	width: 290px;");
document.writeln("    border: 1px solid #0bccd9;");
document.writeln("    color: #c2c2c2;");
document.writeln("    height: 40px;");
document.writeln("    line-height: 40px;");
document.writeln("    padding-left: 10px;");
document.writeln("    font-size: 17px;");
document.writeln("    background: url(images/rbh_rczp01.png) no-repeat 255px center;");
document.writeln("}");
document.writeln(".input2 a {");
document.writeln("    display: block;");
document.writeln("    height: 26px;");
document.writeln("    width: 26px;");
document.writeln("    position: absolute;");
document.writeln("    right: 20px;");
document.writeln("    top: 17px;");
document.writeln("    z-index: 99;");
document.writeln("    background: #000;");
document.writeln("    opacity: 0;");
document.writeln("    filter:alpha(opacity=0);");
document.writeln("}");
document.writeln(".user{");
document.writeln("	position: absolute;");
document.writeln("	right: 72px;");
document.writeln("	top: 0;");
document.writeln("	height: 60px;");
document.writeln("	width: 57px;");
document.writeln("}");
document.writeln(".user a{");
document.writeln("  display: block;");
document.writeln("	height: 27px;");
document.writeln("	width: 27px;");
document.writeln("	margin-left: 17px;");
document.writeln("  margin-top: 17px;");

document.writeln("}");
document.writeln(".ssfl{");
document.writeln("	position: absolute;");
document.writeln("	right: 132px;");
document.writeln("	top: 51px;");
document.writeln("	overflow: hidden;");
document.writeln("	width: 290px;");
document.writeln("	background: #FFFFFF;");
document.writeln("	z-index: 99;");
document.writeln("	display: none;");
document.writeln("}");
document.writeln(".ssfl ul{");
document.writeln("	padding-left: 17px;");
document.writeln("	height: 44px;");
document.writeln("	width: 290px;");
document.writeln("	overflow: hidden;");
document.writeln("	border-bottom: 1px solid #d8d8d8;");
document.writeln("}");
document.writeln(".ssfl ul li{");
document.writeln("	height: 44px;");
document.writeln("	line-height: 44px;");
document.writeln("	float: left;");
document.writeln("	color: #666666;");
document.writeln("	font-size: 15px;");
document.writeln("	background: url(images/rbh_zplb01.png) no-repeat left center;");
document.writeln("	padding-left: 13px;");
document.writeln("	padding-right: 48px;");
document.writeln("}");
document.writeln(".active{");
document.writeln("	background: url(images/rbh_zplb02.png) no-repeat left center !important;");
document.writeln("}");
document.writeln(".sactive{");
document.writeln("	background: url(images/rbh_zplb04.png) no-repeat left center !important;");
document.writeln("}");
document.writeln(".active1{");
document.writeln("	display: block !important;");
document.writeln("}");
document.writeln(".sactive3{");
document.writeln("	color: #0070c9 !important;");
document.writeln("    background: url(images/rbh_zplb04.png) no-repeat left center !important;");
document.writeln("}");
document.writeln(".active3{");
document.writeln("	top: 50px;");
document.writeln("	right: 290px;");
document.writeln("}");
document.writeln(".zslb_r input{");
document.writeln("	color: #FFFFFF !important;");
document.writeln("}");
document.writeln("	/*侧导航*/");
document.writeln("	.side-nav-bg {");
document.writeln("	    width: 0px;");
document.writeln("	    height: 900px;");
document.writeln("	    background-color: rgba(0, 0, 0, .5);");
document.writeln("	    z-index: 2;");
document.writeln("	    position: fixed;");
document.writeln("	    right: 0px;");
document.writeln("	    top: 0px;");
document.writeln("	    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#7f000000, endColorstr=#7f000000);");
document.writeln("	}");
document.writeln("	");
document.writeln("	.side-choice {");
document.writeln("	    width: 214px;");
document.writeln("	    height: 61px;");
document.writeln("	}");
document.writeln("	.input1{");
document.writeln("		position: fixed;");
document.writeln("		top: 0;");
document.writeln("		right: 278px;");
document.writeln("		height: 60px;");
document.writeln("		width: 312px;");
document.writeln("		padding: 10px;");
document.writeln("		display: none;");
document.writeln("		background-color: rgba(0, 0, 0, 0.5);");
document.writeln("	}");
document.writeln("	.input1 input{");
document.writeln("		width: 290px;");
document.writeln("		background-color: rgba(0, 0, 0, 0);");
document.writeln("		_background-color: rgba(0, 0, 0, 0.5);");
document.writeln("		border: 1px solid #0bccd9;");
document.writeln("		color: #c2c2c2;");
document.writeln("		height: 40px;");
document.writeln("		line-height: 40px;");
document.writeln("		padding-left: 10px;");
document.writeln("		font-size: 17px;");
document.writeln("		background: url(images/rbh_rczp01.png) no-repeat 255px center;");
document.writeln("	}");
document.writeln("	.input1 a{");
document.writeln("	display: block;");
document.writeln("	height: 26px;");
document.writeln("	width: 26px;");
document.writeln("	position: absolute;");
document.writeln("	right: 20px;");
document.writeln("	top: 17px;");
document.writeln("background: #000;");
document.writeln("    opacity: 0;");
document.writeln("    filter:alpha(opacity=0);");
document.writeln("}");
document.writeln("	.side-choice ul{");
document.writeln("		overflow: hidden;");
document.writeln("		width: 214px;");
document.writeln("		border-right: 1px solid #FFFFFF;");
document.writeln("		padding-top: 10px;");
document.writeln("		height: 60px;");
document.writeln("	}");
document.writeln("	.side-choice ul li{");
document.writeln("		float: left;");
document.writeln("		height: 40px;");
document.writeln("		width: 40px;");
document.writeln("		margin: 0 5px;");
document.writeln("		cursor: pointer;");
document.writeln("	}");
document.writeln("	.side-choice ul .list1{");
document.writeln("		background: url(\"images/njblh-img2.png\") no-repeat -7px center;");
document.writeln("	}");
document.writeln("	.chimg{");
document.writeln("		background: url(\"images/njblh-img3.png\") no-repeat -11px center !important;");
document.writeln("	}");
document.writeln("	.side-choice ul .list2{");
document.writeln("		background: url(\"images/njblh-img2.png\") no-repeat -57px center;");
document.writeln("	}");
document.writeln("	.side-choice ul .list3{");
document.writeln("		background: url(\"images/njblh-img2.png\") no-repeat -104px center;");
document.writeln("	}");
document.writeln("	.chimg2{");
document.writeln("		background: url(\"images/njblh-img4.png\") no-repeat  center 7px !important;");
document.writeln("	}");
document.writeln("	.side-choice ul .list4{");
document.writeln("		background: url(\"images/njblh-img2.png\") no-repeat -149px center;");
document.writeln("	}");
document.writeln("	");
document.writeln("	.button-right2 {");
document.writeln("	    width: 64px;");
document.writeln("	    height: 61px;");
document.writeln("	    background: url(\"images/njblh-img3.png\") no-repeat;");
document.writeln("	}");
document.writeln("	");
document.writeln("	.side-nav-box {");
document.writeln("	    padding-top: 30px;");
document.writeln("	    width: 100%;");
document.writeln("	    overflow: hidden;");
document.writeln("	    padding-left: 40px;");
document.writeln("	}");
document.writeln("	");
document.writeln("	.side-nav-box a {");
document.writeln("	    color: #ffffff;");
document.writeln("	    font-size:16px");
document.writeln("	}");
document.writeln("	");
document.writeln("	.side-nav-box li {");
document.writeln("	    height: 33px;");
document.writeln("	    line-height: 30px;");
document.writeln("	    margin-top: 20px;");
document.writeln("	}");
document.writeln("	.side-nav-box li:hover div{");
document.writeln("	    width: 64px;");
document.writeln("	    transition: .3s;");
document.writeln("	}");
document.writeln("	.side-xhx {");
document.writeln("	    width: 0px;");
document.writeln("	    height: 3px;");
document.writeln("	    background: url(\"images/rbh_zpxq02.jpg\") center;");
document.writeln("	    transition: .3s;");
document.writeln("	}");
document.writeln("	.erweima{");
document.writeln("		width: 278px;");
document.writeln("		height: 140px;");
document.writeln("		overflow: hidden;");
document.writeln("		background: url(images/njblh-img5.png) no-repeat center;");
document.writeln("		position: absolute;");
document.writeln("		top: 52px;");
document.writeln("		left: 0;");
document.writeln("		display: none;");
document.writeln("	}");
document.writeln("	");
document.writeln("	");
document.writeln("		/*footer*/");
document.writeln("		.footer{");
document.writeln("		    font-size: 13px;");
document.writeln("		    color: #8dc7ff;");
document.writeln("		    text-align: center;");
document.writeln("		    line-height: 30px;");
document.writeln("		}");
document.writeln("		.footer span{");
document.writeln("			padding-right: 32px;");
document.writeln("		}");
document.writeln(".local{");
document.writeln("	color: #FFFFFF !important;");
document.writeln("	}");
document.writeln(".local a{");
document.writeln("	color: #FFFFFF !important;");
document.writeln("}");

document.writeln(".tuichu{");
document.writeln("		 position: absolute;");
document.writeln("	    right: 66px;");
document.writeln("	    top: 4px;");
document.writeln("	    height: 17px;");
document.writeln("	    width: 34px;");
document.writeln("	}");
document.writeln("	.tuichu{");
document.writeln("		width: 34px;");
document.writeln("	    background: url(images/rbh_tuichu.png) no-repeat center;");
document.writeln("	    height: 17px;");
document.writeln("	    display: block;");
document.writeln("	}");
document.writeln(".spart1{");
document.writeln("	width: 290px;");
document.writeln("	color: #333333;");
document.writeln("	font-size: 13px;");
document.writeln("	padding: 10px 20px;");
document.writeln("	display: none;");
document.writeln("	padding-bottom: 70px;");
document.writeln("	overflow: hidden;");
document.writeln("}");
document.writeln(".spart1 form{");
document.writeln("	overflow: hidden;");
document.writeln("	margin-top: 10px;");
document.writeln("}");
document.writeln(".spart1 form input{");
document.writeln("	width: 353px;");
document.writeln("	height: 36px;");
document.writeln("	line-height: 36px;");
document.writeln("	color: #333333;");
document.writeln("	border: 1px solid #buttonface;");
document.writeln("	background: #FFFFFF;");
document.writeln("	padding-left: 12px;");
document.writeln("}");
document.writeln(".spart1 div{");
document.writeln("	width: 50%;");
document.writeln("	float: left;");
document.writeln("	overflow: hidden;");
document.writeln("	line-height: 20px;	");
document.writeln("}");
document.writeln(".spart1 p{");
document.writeln("	float: left;");
document.writeln("	margin-bottom: 20px;");
document.writeln("	padding-left: 17px;");
document.writeln("	padding-right: 10px;");
document.writeln("	background: url(images/rbh_zplb03.png) no-repeat left center;");
document.writeln("	cursor: pointer;");
document.writeln("}");
document.writeln(".ssfl .btn{");
document.writeln("	position: absolute;");
document.writeln("	height: 30px;");
document.writeln("	width: 104px;;");
document.writeln("	bottom: 26px;");
document.writeln("	text-align: center;");
document.writeln("	line-height: 30px;");
document.writeln("	cursor: pointer;");
document.writeln("}");
document.writeln("#sbtn_ok1{");
document.writeln("	left: 20px;");
document.writeln("	background: #0d77cc;");
document.writeln("	color: #FFFFFF;");
document.writeln("}");
document.writeln("#sbtn_no1{");
document.writeln("	right: 20px;");
document.writeln("	background: #f2f2f2;");
document.writeln("	color: #666666;");
document.writeln("}");
document.writeln("	</style>");
document.writeln("<div class=\"input2\">");
document.writeln("		    <input id=\"int1\" type=\"text\" onkeydown=\"if(event.keyCode==13) return searchZslb2();\" name=\"int2\"  value=\"请输入关键词\" onclick=\"if(value==defaultValue){value=\'\'}\" onblur=\"if(!value){value=defaultValue;}\">");
document.writeln("		   	<a onclick=\"searchZslb2()\" href=\"javascript:void(0)\"></a>");
document.writeln("		</div>");
document.writeln("		<div class=\"user\">");
document.writeln("			<a id=\"loginuser\" href=\"/zsgl/front/personal_list.do\"></a>");
document.writeln("		</div>");
document.writeln("  <a id=\"tuichu\"  href=\"/zsgl/front/layout.do\" style=\"display:none\"><div class=\"tuichu\"></div></a>");
document.writeln("		<div class=\"ssfl\">");
document.writeln("		    		<ul>");
document.writeln("		    			<li id=\"zsqy\">按展商区域</li>");
document.writeln("		    			<li id=\"\">按展商分类</li>");
document.writeln("		    		</ul>");
document.writeln("<div class=\"spart1\">");
document.writeln("		    			<div><p>物联网</p></div>");
document.writeln("		    			<div><p>信息安全</p></div>");
document.writeln("		    			<div><p>智慧城市</p></div>");
document.writeln("		    			<div><p>物联网</p></div>");
document.writeln("		    			<div><p>信息安全</p></div>");
document.writeln("		    			<div><p>智慧城市</p></div>");
document.writeln("		    		</div>");
document.writeln("		    		<div class=\"spart1\">");
document.writeln("		    			<div><p>大数据</p></div>");
document.writeln("		    			<div><p>物联网</p></div>");
document.writeln("		    			<div><p>信息安全</p></div>");
document.writeln("		    			<div><p>云计算云计算云计算云计算云计算云计算</p></div>");
document.writeln("		    			<div><p>大数据</p></div>");
document.writeln("		    			<div><p>物联网</p></div>");
document.writeln("		    			<div><p>信息安全</p></div>");
document.writeln("		    			<div><p>智慧城市</p></div>");
document.writeln("		    		</div>");
document.writeln("					<div class=\"btn\" id=\"sbtn_ok1\">确  定</div>");
document.writeln("			         <div class=\"btn\" id=\"sbtn_no1\">取  消</div>");
document.writeln("		    	</div>");
document.writeln("		    <div class=\"head-bg\">");
document.writeln("		        <div class=\"logo bt-left\">");
document.writeln("		");
document.writeln("		        </div>");
document.writeln("		        <div class=\"button-right bt-right\" id=\"button1\">");
document.writeln("		        </div>");
document.writeln("		    </div>");
document.writeln("		    <div class=\"bt-clear\"></div>");
document.writeln("		    <div class=\"side-nav-bg bt-right\" id=\"sidenav\">		   ");
document.writeln("		        <div style=\"width: 100%;overflow: hidden;height: 61px;\">");
document.writeln("		            <div class=\"side-choice bt-left\">");
document.writeln("						<ul>");
document.writeln("							<li class=\"list1\"></li>");  
document.writeln("							<li class=\"list2\"><a href=\"/zsgl/front/personal_list.do\" style=\"float: left;height: 100%;width: 100%;\"></a></li>");
document.writeln("							<li class=\"list3\"></li>");
document.writeln("							<a href=\"http://wpa.qq.com/msgrd?v=3&uin=1950074034&site=qq&menu=yes\"><li class=\"list4\"></li></a>");
document.writeln("						</ul>");
document.writeln("		            </div>");
document.writeln("		            <div class=\"button-right2 bt-right\" id=\"button2\">");
document.writeln("		");
document.writeln("		          	</div>");
document.writeln("		            <div class=\"bt-clear\"></div>");
document.writeln("		        </div>");
document.writeln("		        <!--导肮部分-->");
document.writeln("		        <ul class=\"side-nav-box\" id=\"side-nav-box\">");
document.writeln("		            <li><a href=\"/zsgl/front/index.do\">首页</a>");
document.writeln("		                <div class=\"side-xhx\" style=\"max-width: 30px\"></div>");
document.writeln("		            </li>");
document.writeln("		            <li><a href=\"/zsgl/front/showzslb.do?pavilionid=ztg\">展览中心</a>");
document.writeln("                <div class=\"side-xhx\"></div>");
document.writeln("		            </li>");
document.writeln("		            <li><a href=\"/zsgl/front/showActivity.do\">活动中心</a>");
document.writeln("                		<div class=\"side-xhx\"></div>");
document.writeln("           		 </li>");
document.writeln("            		<li><a href=\"/zsgl/front/product_list.do\">交易中心</a>");
document.writeln("               		 <div class=\"side-xhx\"></div>");
document.writeln("           		 </li>");  //javascript:hover_change(4)
document.writeln("		            <li><a href=\"/zsgl/front/personal_list.do\">个人中心</a>");
document.writeln("		                <div class=\"side-xhx\"></div>");
document.writeln("		            </li>");
document.writeln("		        </ul>");
document.writeln("		        <div class=\"erweima\"></div>");
document.writeln("		    </div>");
document.writeln("			<div class=\"input1\">");
document.writeln("		        <input type=\"text\" onkeydown='if(event.keyCode==13) return searchZslb1();' name=\"int1\" id=\"int1\" value=\"请输入关键词\" onclick=\"if(value==defaultValue){value=\'\'}\" onblur=\"if(!value){value=defaultValue;}\"/>");
document.writeln("		   		<a onclick=\"searchZslb1()\" href=\"javascript:void(0)\"></a>");
document.writeln("			</div>");
document.writeln("		<script type=\"text/javascript\">");
document.writeln("			$(function () {");
document.writeln("			    click_change();");
document.writeln("			})");
document.writeln("			function searchZslb1() {");
document.writeln("			var key = $(\"input[name='int1']\").val();	");
document.writeln("			if(key==\"请输入关键词\"){	");
document.writeln("			key=\"\";	");
document.writeln("			}	");
document.writeln("       	      var biaoqian = $(\'.active\').attr(\'id\');");
document.writeln("              if(biaoqian==\'zsqy\'){");
document.writeln("	               url=\'/zsgl/front/searchZsqylb.do?key=\'+encodeURI(key)+\'&pagesize=3&pageid=1\';");
document.writeln("               }else{");
document.writeln("	               url=\'/zsgl/front/searchZslb.do?key=\'+encodeURI(key)+\'&pagesize=3&pageid=1\';");
document.writeln("               }");
document.writeln("				location.href=url;");
document.writeln("			}");
document.writeln("			function searchZslb2() {");
document.writeln("			var key = $(\"input[name='int2']\").val();	");
document.writeln("			if(key==\"请输入关键词\"){	");
document.writeln("			key=\"\";	");
document.writeln("			}	");
document.writeln("              var biaoqian = $(\'.active\').attr(\'id\');");
document.writeln("              if(biaoqian==\'zsqy\'){");
document.writeln("	               url=\'/zsgl/front/searchZsqylb.do?key=\'+encodeURI(key)+\'&pagesize=3&pageid=1\';");
document.writeln("               }else{");
document.writeln("	               url=\'/zsgl/front/searchZslb.do?key=\'+encodeURI(key)+\'&pagesize=3&pageid=1\';");
document.writeln("               }");
document.writeln("				location.href=url;");
document.writeln("			}");
document.writeln("			function click_change() {");
document.writeln("				var seach = $(\'.side-choice ul .list1\');");
document.writeln("			    var input1 = $(\'.input1\');");
document.writeln("			    var tem = true;");
document.writeln("			    seach.click(function(){");
document.writeln("			    	tem = !tem;");
document.writeln("			    	if (!tem) {");
document.writeln("			    		seach.addClass(\'chimg\');");
document.writeln("			    		input1.css({\'display\':\"block\"});");
document.writeln("			    	} else{");
document.writeln("			    		seach.removeClass(\'chimg\');");
document.writeln("			    		input1.css({\'display\':\"none\"});");
document.writeln("			    	}");
document.writeln("			    })");
document.writeln("var ssfl = $(\'.ssfl\');");
document.writeln("input1.click(function(){");
document.writeln("		ssfl.eq(0).addClass(\'active1 active3\');");
document.writeln("	})");
document.writeln("				var changeImg = $(\'.side-choice ul .list3\');");
document.writeln("			    var erweima = $(\'.erweima\');");
document.writeln("			    var tem1 = true;");
document.writeln("			    changeImg.click(function(){");
document.writeln("			    	tem1 = !tem1;");
document.writeln("			    	if (!tem1) {");
document.writeln("			    		changeImg.addClass(\'chimg2\');");
document.writeln("			    		erweima.css({\'display\':\"block\"});");
document.writeln("			    	} else{");
document.writeln("			    		changeImg.removeClass(\'chimg2\');");
document.writeln("			    		erweima.css({\'display\':\"none\"});");
document.writeln("			    	}");
document.writeln("			    })");
document.writeln("			    ");
document.writeln("			    var bt1 = $(\"#button1\");");
document.writeln("			    var bt2 = $(\"#button2\");");
document.writeln("			    var sideNav = $(\"#sidenav\");");
document.writeln("    var input2 = $(\'.input2\');");
document.writeln("			    bt1.click(function () {");
document.writeln("			        sideNav.animate({width: \"278px\"}, 500);");
document.writeln("			        bt1.animate({width: \"0\"}, 500);");
document.writeln("			        bt2.animate({width: \"64px\"}, 500);");
document.writeln("input2.hide()");
document.writeln("			    })");
document.writeln("			    bt2.click(function () {");
document.writeln("			    	tem = true;");
document.writeln("			    	tem1 = true;");
document.writeln("input2.show(500);");
document.writeln("			ssfl.eq(0).removeClass(\'active1 active3\');");
document.writeln("			    	erweima.css({\'display\':\"none\"});");
document.writeln("			    	input1.css({\'display\':\"none\"});");
document.writeln("			    	changeImg.removeClass(\'chimg2\');");
document.writeln("			    	seach.removeClass(\'chimg\');");
document.writeln("			        sideNav.animate({width: \"0\"}, 500);");
document.writeln("			        bt1.animate({width: \"65px\"}, 500);");
document.writeln("			        bt2.animate({width: \"0px\"}, 500);");
document.writeln("			    })");
document.writeln("			}");
document.writeln("        $(document).ready(function(){");
document.writeln("    	 $.ajax({");
document.writeln("		    	 url: \"../../zsgl/front/isLogined.do\",");
document.writeln("				 data:{},");
document.writeln("				async:false,");
document.writeln("				type:\"post\",");
document.writeln("				  success: function(result){");
document.writeln("                   if(result==1){");
document.writeln("                	   $(\"#loginuser\").css(\'background\',\'url(images/rbh_user1.png) no-repeat center\');");
document.writeln("                    $(\"#tuichu\").css(\'display\',\'block\');");
document.writeln("                   }else if(result == 2){");
document.writeln("                	   $(\"#loginuser\").css(\'background\',\'url(images/rbh_user.png) no-repeat center\');");

document.writeln("                   }");
document.writeln("");
document.writeln("				  }");
document.writeln("				});");
document.writeln("	}); ");
document.writeln("/*切换*/");
document.writeln("			function hover_change(show_num) {	");
document.writeln("	   			var changeLi=$(\"#side-nav-box li\");");
document.writeln("	    		var changeXhx=$(\".side-xhx\");");
document.writeln("	    		");
document.writeln("    			for(var i=0;i<changeLi.length;i++){");
document.writeln("	      			if(i===show_num){");
document.writeln("	           			changeXhx.eq(show_num).css({width:\"64px\"});");
document.writeln("	       			}else {");
document.writeln("	           			changeXhx.eq(i).css({width:\"0\"});");
document.writeln("	       			}");
document.writeln("	       			if(i===0){");
document.writeln("	           			changeXhx.eq(show_num).css({width:\"30px\"});");
document.writeln("	       			}");
document.writeln("    			}");
document.writeln("			}");

document.writeln("$(function(){");
document.writeln("			    var input1 = $(\'.input1\');");
document.writeln("		var In_li = $(\'.ssfl ul li\');");
document.writeln("		var int1 = $(\'#int1\');");
document.writeln("		var ssfl = $(\'.ssfl\');");
document.writeln("var part1 = $(\'.spart1\');");
document.writeln("var In_p = $(\'.spart1 div p\');");
document.writeln("		var num;");
document.writeln("part1.eq(0).addClass(\'active1\');");
document.writeln("		int1.click(function(){");
document.writeln("			ssfl.eq(0).addClass(\'active1\');");
document.writeln("		})");
document.writeln("		function stopPropagation(e) { ");
document.writeln("			if (e.stopPropagation) {");
document.writeln("				e.stopPropagation(); ");
document.writeln("			}else{");
document.writeln("				e.cancelBubble = true; ");
document.writeln("			}");
document.writeln("		} 	");
document.writeln("		$(document).bind(\'click\',function(){ ");
document.writeln("			ssfl.eq(0).removeClass(\'active1\');");
document.writeln("		}); ");
document.writeln("			");
document.writeln("		int1.bind(\'click\',function(e){ ");
document.writeln("			stopPropagation(e); ");
document.writeln("		}); ");
document.writeln("		input1.bind(\'click\',function(e){ ");
document.writeln("			stopPropagation(e); ");
document.writeln("		}); ");
document.writeln("		ssfl.bind(\'click\',function(e){ ");
document.writeln("			stopPropagation(e); ");
document.writeln("		});");
document.writeln("		");
document.writeln("		In_li.click(function(){");
document.writeln("In_p.removeClass(\'sactive3\');");
document.writeln("part1.eq($(this).index()).addClass(\'active1\').siblings().removeClass(\'active1\');");
document.writeln("			if (In_li.eq($(this).index()).hasClass(\'active\')) {");
document.writeln("				In_li.eq($(this).index()).removeClass(\'active\');");
document.writeln("			}else{");
document.writeln("				In_li.eq($(this).index()).addClass(\'active\').siblings().removeClass(\'active\');");
document.writeln("			}");
document.writeln("		})");
document.writeln("for (var i=0;i<In_p.length;i++) {");
document.writeln("		In_p[i].index = i;");
document.writeln("		In_p[i].onclick = function(){");
document.writeln("			if (In_p[this.index].className != \'sactive3\') {");
document.writeln("				In_p[this.index].className = \'sactive3\';");
document.writeln("			} else{");
document.writeln("				In_p[this.index].className = \'none\';");
document.writeln("			}");
document.writeln("		}");
document.writeln("	}");
document.writeln("	})");
document.writeln("		</script>");