document.writeln("<div class=\'footer\'>");
document.writeln("			<div class=\'container\'>");
document.writeln("				<div class=\'row \'>");
document.writeln("					<div class=\'col-md-3 col-sm-3 footer_logo\'>");
document.writeln("						<img src=\'images/ARXTA2.png\'/>");
document.writeln("					</div>");
document.writeln("					<ul class=\'nav navbar-nav text-center col-md-5 col-sm-5\' id=\'footer_li\'>");
document.writeln("       					<li class=\'footer_active\'><a href=\'\'>Item Selected</a></li>");
document.writeln("        				<li><a href=\'#\'>Item</a></li>");
document.writeln("        				<li><a href=\'#\'>Item</a></li>");
document.writeln("        				<li><a href=\'#\'>Item</a></li>");
document.writeln("        				<li><a href=\'#\'>Item</a></li>");
document.writeln("      			    </ul>");
document.writeln("      			    <div class=\'footer_search_box col-md-4 col-sm-3\'>");
document.writeln("      			    	<input type=\'text\' class=\'form-control\' placeholder=\'Search\'/>");
document.writeln("      			    	<span class=\'glyphicon glyphicon-search search_icon\' style=\'margin-right: 20px;cursor: pointer;\'></span>");
document.writeln("      			    </div>");
document.writeln("				</div>");
document.writeln("				<div class=\'row rele_box\'>");
document.writeln("					<div class=\'col-md-4 col-sm-4 col-md-offset-8 col-sm-offset-8\'>");
document.writeln("						<div class=\'col-md-5 rele_text col-xs-5\'>FOLLOW US：</div>");
document.writeln("						<div class=\'col-md-7 col-xs-7\'>");
document.writeln("							<div class=\'rele_icon\'><img src=\'images/facebook.png\'/></div>");
document.writeln("							<div class=\'rele_icon\'><img src=\'images/carmera.png\'/></div>");
document.writeln("							<div class=\'rele_icon\'><img src=\'images/PPP.png\'/></div>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("");
document.writeln("				<div class=\'row footer_bottom\'>");
document.writeln("					<div class=\'col-md-4\'>&copy;2017 Arxta All rights reserved.</div>");
document.writeln("					<div class=\'col-md-4\'>Privacy Policy | Terms & Conditions</div>");
document.writeln("				</div>");
document.writeln("");
document.writeln("			</div>");
document.writeln("		</div>");
