document.writeln("<nav class=\'navbar navbar-default\' id=\'navbar\'>");
document.writeln("			<div class=\'container\'>");
document.writeln("				<div class=\'row\'>");
document.writeln("					<div class=\'navbar-header col-md-2 col-sm-2\'>");
document.writeln("						<button type=\'button\' class=\'navbar-toggle collapsed\' data-toggle=\'collapse\' data-target=\'#nav_li\' aria-expanded=\'false\'>");
document.writeln("					        <span class=\'icon-bar\'></span>");
document.writeln("					        <span class=\'icon-bar\'></span>");
document.writeln("					        <span class=\'icon-bar\'></span>");
document.writeln("					    </button>");
document.writeln("						<a href=\'index.html\' class=\'logo_box\'>");
document.writeln("							<img src=\'images/ARXTA.png\'/>");
document.writeln("						</a>");
document.writeln("					</div>");
document.writeln("					<div class=\'collapse navbar-collapse\' id=\'nav_li\'>");
document.writeln("						<ul class=\'nav navbar-nav text-center col-md-5 col-sm-5\'>");
document.writeln("	       					<li class=\'active\'><a href=\'customMade.html\'>SHOP</a></li>");
document.writeln("	        				<li><a href=\'customMadeI.html\'>CREATE</a></li>");
document.writeln("	        				<li><a href=\'show.html\'>SHOW</a></li>");
document.writeln("	        				<li><a href=\'introduce.html\'>HOW IT WORKS</a></li>");
document.writeln("	      				</ul>");
document.writeln("	      				<form class=\'col-md-2 col-sm-2 col-xs-12 nav_search_box\'>");
document.writeln("					        <input type=\'text\' class=\'form-control\' placeholder=\'Search this site\'>");
document.writeln("					    </form>");
document.writeln("					    <div class=\'col-md-1 col-sm-1 text-center hidden-xs\'>");
document.writeln("					    	<a href=\'cart.html\'>");
document.writeln("						    	<i class=\'iconfont icon-gouwuche\' style=\'font-size: 28px;line-height: 50px;position: relative;color: #000; \'>");
document.writeln("						    		<span class=\'cart_badge\'>1</span>");
document.writeln("						    	</i>");
document.writeln("					    	</a>");
document.writeln("					    </div>");
document.writeln("					    <div class=\'col-md-2  col-sm-5\'>");
document.writeln("					    	<a href=\'account.html\'><div class=\'head_img\'><img src=\'images/avatar.png\'/></div></a>");
document.writeln("					    	<div class=\'register\'>Register | Log in</div>");
document.writeln("					    	");
document.writeln("					    </div>");
document.writeln("				    </div>");
document.writeln("				</div>");
document.writeln("				");
document.writeln("			</div>");
document.writeln("		</nav>");
